### ISSUE TITLE
Double free or corruption crash

### ISSUE THREAD

**Issue by blurpy** [QuantAsylum/QA40x#15]
I get this crash quite often in v0.9999 (newest for Linux). It's printed in the terminal I use to start the Analyzer.

```
double free or corruption (out)

=================================================================
        Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
        0x55cf0da54b31 - /usr/bin/mono : 
        0x55cf0da54ec9 - /usr/bin/mono : 
        0x55cf0da02f51 - /usr/bin/mono : 
        0x55cf0da540c4 - /usr/bin/mono : 
        0x7f0abcb55970 - /lib64/libpthread.so.0 : 
        0x7f0abc993322 - /lib64/libc.so.6 : gsignal
        0x7f0abc97c864 - /lib64/libc.so.6 : abort
        0x7f0abc9d5b17 - /lib64/libc.so.6 : 
        0x7f0abc9dd73c - /lib64/libc.so.6 : 
        0x7f0abc9defc0 - /lib64/libc.so.6 : 
        0x7f0abc9e27f8 - /lib64/libc.so.6 : cfree
        0x7f0ab90eb006 - /lib64/libfontconfig.so.1 : 
        0x7f0ab90eb0d3 - /lib64/libfontconfig.so.1 : FcPatternDestroy
        0x7f0ab9603139 - /lib64/libgdiplus.so.0 : GdipDeleteFontFamily
        0x7f0ab96032b7 - /lib64/libgdiplus.so.0 : GdipDeleteFont
        0x4027bba3 - Unknown

=================================================================
        Telemetry Dumper:
=================================================================
```

The stack trace isn't very detailed, so not sure if it's much help.

I started having this issue when adding support for averages during sweeps in QA40x Web.
I'm trying to amplitude sweep from -40dBV to 18dBV with 20 averages, and it's less than 50% chance of completing a sweep before it crashes.

When it crashes the Analyzer looks like it's processing, but nothing happens. Both the Analyzer window and the Console window are frozen.

![Screenshot_20211111_183050](https://user-images.githubusercontent.com/186016/141342999-50e26db2-4630-46a5-9464-c8557e53bc56.png)

The request is hanging, so the browser does not display any error messages.

![Screenshot_20211111_183142](https://user-images.githubusercontent.com/186016/141343240-0aecee68-5e24-4fc0-8051-995f991fd6e6.png)

The Link LED on the QA402 turns off.

To get started again I have to kill the application and unplug the QA402 to get it back to life.

**Comment by blurpy** [comment]
I got a different crash now. This time the Analyzer window disappeared. The LEDs on the QA402 turned off.

```
=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
        0x55ea6876eb31 - /usr/bin/mono : 
        0x55ea6876eec9 - /usr/bin/mono : 
        0x55ea6871cf51 - /usr/bin/mono : 
        0x55ea6876820d - /usr/bin/mono : 
        0x7fc48752d085 - /lib64/libc.so.6 : 
        0x55ea6981fcb0 - Unknown

=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x140482016413248x from 0x140481614796352x
Pkilling 0x140482059204416x from 0x140481614796352x
Pkilling 0x140481612166720x from 0x140481614796352x
Pkilling 0x140481631606336x from 0x140481614796352x
Pkilling 0x140481607964224x from 0x140481614796352x
Pkilling 0x140481623201344x from 0x140481614796352x
Pkilling 0x140481618998848x from 0x140481614796352x
Pkilling 0x140481635808832x from 0x140481614796352x
Pkilling 0x140481627403840x from 0x140481614796352x
Pkilling 0x140481900443200x from 0x140481614796352x
Pkilling 0x140481884542528x from 0x140481614796352x
Pkilling 0x140481873520192x from 0x140481614796352x
Pkilling 0x140481895740992x from 0x140481614796352x
Pkilling 0x140481629505088x from 0x140481614796352x
Pkilling 0x140481625302592x from 0x140481614796352x
Pkilling 0x140481621100096x from 0x140481614796352x
Pkilling 0x140481605862976x from 0x140481614796352x
Pkilling 0x140481610065472x from 0x140481614796352x
Pkilling 0x140481633707584x from 0x140481614796352x
Pkilling 0x140481616897600x from 0x140481614796352x
Entering thread summarizer pause from 0x140481614796352x
Finished thread summarizer pause from 0x140481614796352x.
Failed to create breadcrumb file (null)/crash_hash_0xd5e6c8e68

Waiting for dumping threads to resume

=================================================================
        External Debugger Dump:
=================================================================
[New LWP 7898]
[New LWP 7899]
[New LWP 7900]
[New LWP 7901]
[New LWP 7902]
[New LWP 7903]
[New LWP 7913]
[New LWP 8495]
[New LWP 8496]
[New LWP 8497]
[New LWP 8498]
[New LWP 8499]
[New LWP 8500]
[New LWP 8501]
[New LWP 8502]
[New LWP 8503]
[New LWP 8504]
[New LWP 8505]
[New LWP 8506]
[New LWP 8507]
[New LWP 8508]
[New LWP 8509]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007fc4874bf59f in poll () from /lib64/libc.so.6
  Id   Target Id                                          Frame 
* 1    Thread 0x7fc4873c7740 (LWP 7896) "mono"            0x00007fc4874bf59f in poll () from /lib64/libc.so.6
  2    Thread 0x7fc486bff640 (LWP 7898) "SGen worker"     0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  3    Thread 0x7fc484af8640 (LWP 7899) "Finalizer"       0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  4    Thread 0x7fc47dc5f640 (LWP 7900) "mono"            0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  5    Thread 0x7fc47d7e3640 (LWP 7901) "Thread Pool I/O" 0x00007fc4874bf59f in poll () from /lib64/libc.so.6
  6    Thread 0x7fc47d536640 (LWP 7902) "libusb_event"    0x00007fc4874bf59f in poll () from /lib64/libc.so.6
  7    Thread 0x7fc47cd35640 (LWP 7903) "mono"            0x00007fc4874bf59f in poll () from /lib64/libc.so.6
  8    Thread 0x7fc46dbfd640 (LWP 7913) "Timer-Scheduler" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  9    Thread 0x7fc46d5fa640 (LWP 8495) "Thread Pool I/O" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  10   Thread 0x7fc46d1f8640 (LWP 8496) "Thread Pool Wor" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  11   Thread 0x7fc46d3f9640 (LWP 8497) "Thread Pool Wor" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  12   Thread 0x7fc46c571640 (LWP 8498) "Thread Pool Wor" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  13   Thread 0x7fc46d9fc640 (LWP 8499) "Thread Pool Wor" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  14   Thread 0x7fc46c370640 (LWP 8500) "Thread Pool Wor" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  15   Thread 0x7fc47c2b2640 (LWP 8501) "Thread Pool Wor" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  16   Thread 0x7fc46c973640 (LWP 8502) "Thread Pool Wor" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  17   Thread 0x7fc46c772640 (LWP 8503) "Thread Pool Wor" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  18   Thread 0x7fc46cbf5640 (LWP 8504) "Thread Pool Wor" 0x00007fc487496b1f in wait4 () from /lib64/libc.so.6
  19   Thread 0x7fc46cff7640 (LWP 8505) "Thread Pool Wor" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  20   Thread 0x7fc46ddfe640 (LWP 8506) "Thread Pool Wor" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  21   Thread 0x7fc46dfff640 (LWP 8507) "Thread Pool Wor" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  22   Thread 0x7fc46cdf6640 (LWP 8508) "Thread Pool Wor" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0
  23   Thread 0x7fc46d7fb640 (LWP 8509) "Thread Pool Wor" 0x00007fc4875cb9da in __futex_abstimed_wait_common64 () from /lib64/libpthread.so.0

Thread 23 (Thread 0x7fc46d7fb640 (LWP 8509) "Thread Pool Wor"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c7d83 in __new_sem_wait_slow64.constprop.0 () at /lib64/libpthread.so.0
#2  0x000055ea689701b9 in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 22 (Thread 0x7fc46cdf6640 (LWP 8508) "Thread Pool Wor"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c7d83 in __new_sem_wait_slow64.constprop.0 () at /lib64/libpthread.so.0
#2  0x000055ea689701b9 in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 21 (Thread 0x7fc46dfff640 (LWP 8507) "Thread Pool Wor"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c7d83 in __new_sem_wait_slow64.constprop.0 () at /lib64/libpthread.so.0
#2  0x000055ea689701b9 in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 20 (Thread 0x7fc46ddfe640 (LWP 8506) "Thread Pool Wor"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c7d83 in __new_sem_wait_slow64.constprop.0 () at /lib64/libpthread.so.0
#2  0x000055ea689701b9 in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 19 (Thread 0x7fc46cff7640 (LWP 8505) "Thread Pool Wor"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c5280 in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#2  0x000055ea689cd23d in  ()
#3  0x000055ea6892739a in  ()
#4  0x000055ea68928ab9 in  ()
#5  0x000055ea689648f1 in  ()
#6  0x000055ea688a83f4 in  ()
#7  0x000000004175f1ca in  ()
#8  0x00007fc486cf8450 in  ()
#9  0xffffffffffffffff in  ()
#10 0x00007fc486cf8450 in  ()
#11 0xffffffffffffffff in  ()
#12 0x00007fc486cf8450 in  ()
#13 0x00007fc46cff6928 in  ()
#14 0x00007fc46cff5d00 in  ()
#15 0x00007fc46cff5c70 in  ()
#16 0x00007fc486cf8450 in  ()
#17 0x000000004175f070 in  ()
#18 0x00007fc4640bd808 in  ()
#19 0x0000000000000000 in  ()

Thread 18 (Thread 0x7fc46cbf5640 (LWP 8504) "Thread Pool Wor"):
#0  0x00007fc487496b1f in wait4 () at /lib64/libc.so.6
#1  0x000055ea6876edb1 in  ()
#2  0x000055ea6876eec9 in  ()
#3  0x000055ea6871cf51 in  ()
#4  0x000055ea6876820d in  ()
#5  0x00007fc48752d085 in __strlen_avx2 () at /lib64/libc.so.6
#6  0x000055ea6981fcb0 in  ()
#7  0x00007fc48745a1a3 in strdup () at /lib64/libc.so.6
#8  0x00007fc47fe021e7 in cairo_surface_get_font_options () at /lib64/libcairo.so.2
#9  0x00007fc47fdc1ec1 in  () at /lib64/libcairo.so.2
#10 0x00007fc47fdc1f95 in  () at /lib64/libcairo.so.2
#11 0x00007fc47fe1145c in cairo_font_extents () at /lib64/libcairo.so.2
#12 0x00007fc4840f7f5e in  () at /lib64/libgdiplus.so.0
#13 0x00007fc4840e8e95 in GdipMeasureString () at /lib64/libgdiplus.so.0
#14 0x00000000414496de in  ()
#15 0x00007fc46cbf3f48 in  ()
#16 0x0000000000000000 in  ()

Thread 17 (Thread 0x7fc46c772640 (LWP 8503) "Thread Pool Wor"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c7d83 in __new_sem_wait_slow64.constprop.0 () at /lib64/libpthread.so.0
#2  0x000055ea689701b9 in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 16 (Thread 0x7fc46c973640 (LWP 8502) "Thread Pool Wor"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c7d83 in __new_sem_wait_slow64.constprop.0 () at /lib64/libpthread.so.0
#2  0x000055ea689701b9 in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 15 (Thread 0x7fc47c2b2640 (LWP 8501) "Thread Pool Wor"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c7d83 in __new_sem_wait_slow64.constprop.0 () at /lib64/libpthread.so.0
#2  0x000055ea689701b9 in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 14 (Thread 0x7fc46c370640 (LWP 8500) "Thread Pool Wor"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c7d83 in __new_sem_wait_slow64.constprop.0 () at /lib64/libpthread.so.0
#2  0x000055ea689701b9 in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 13 (Thread 0x7fc46d9fc640 (LWP 8499) "Thread Pool Wor"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c7d83 in __new_sem_wait_slow64.constprop.0 () at /lib64/libpthread.so.0
#2  0x000055ea689701b9 in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 12 (Thread 0x7fc46c571640 (LWP 8498) "Thread Pool Wor"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c7d83 in __new_sem_wait_slow64.constprop.0 () at /lib64/libpthread.so.0
#2  0x000055ea689701b9 in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 11 (Thread 0x7fc46d3f9640 (LWP 8497) "Thread Pool Wor"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c7d83 in __new_sem_wait_slow64.constprop.0 () at /lib64/libpthread.so.0
#2  0x000055ea689701b9 in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 10 (Thread 0x7fc46d1f8640 (LWP 8496) "Thread Pool Wor"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c7d83 in __new_sem_wait_slow64.constprop.0 () at /lib64/libpthread.so.0
#2  0x000055ea689701b9 in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 9 (Thread 0x7fc46d5fa640 (LWP 8495) "Thread Pool I/O"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c5584 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#2  0x000055ea689cd1da in  ()
#3  0x000055ea689d843c in  ()
#4  0x000055ea68970eb3 in  ()
#5  0x000055ea68918c97 in  ()
#6  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#7  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 8 (Thread 0x7fc46dbfd640 (LWP 7913) "Timer-Scheduler"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c5584 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#2  0x000055ea689cd1da in  ()
#3  0x000055ea6892739a in  ()
#4  0x000055ea68928c88 in  ()
#5  0x000055ea68929570 in  ()
#6  0x000055ea6891a22a in  ()
#7  0x000055ea688aa642 in  ()
#8  0x0000000040673c92 in  ()
#9  0x00007fc486f66480 in  ()
#10 0x00007fc486f663e0 in  ()
#11 0x0000000000000000 in  ()

Thread 7 (Thread 0x7fc47cd35640 (LWP 7903) "mono"):
#0  0x00007fc4874bf59f in poll () at /lib64/libc.so.6
#1  0x00007fc47d570c35 in  () at /lib64/libusb-1.0.so
#2  0x00007fc47d572407 in libusb_handle_events_timeout_completed () at /lib64/libusb-1.0.so
#3  0x000000004163adf4 in  ()
#4  0x00007fc486ecaef8 in  ()
#5  0x00007fc47cd34ab0 in  ()
#6  0x00007fc486ecae78 in  ()
#7  0x00007fc486ecaa90 in  ()
#8  0x00007fc486ecaa90 in  ()
#9  0x00007fc486ecaa90 in  ()
#10 0x00007fc486ecaa90 in  ()
#11 0x00007fc486ecaa90 in  ()
#12 0x00007fc474002690 in  ()
#13 0x00007fc47cd34ab0 in  ()
#14 0x00007fc47cd34970 in  ()
#15 0x00007fc47cd34901 in  ()
#16 0x0000000000000000 in  ()

Thread 6 (Thread 0x7fc47d536640 (LWP 7902) "libusb_event"):
#0  0x00007fc4874bf59f in poll () at /lib64/libc.so.6
#1  0x00007fc47d56e02e in  () at /lib64/libusb-1.0.so
#2  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#3  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 5 (Thread 0x7fc47d7e3640 (LWP 7901) "Thread Pool I/O"):
#0  0x00007fc4874bf59f in poll () at /lib64/libc.so.6
#1  0x000055ea6891f838 in  ()
#2  0x000055ea6892081b in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7fc47dc5f640 (LWP 7900) "mono"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c5280 in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#2  0x000055ea689cd23d in  ()
#3  0x000055ea6892739a in  ()
#4  0x000055ea68928ab9 in  ()
#5  0x000055ea68929570 in  ()
#6  0x000055ea6891a22a in  ()
#7  0x000055ea688aa642 in  ()
#8  0x0000000040673c92 in  ()
#9  0x00007fc486f59680 in  ()
#10 0x00007fc486cc6ad8 in  ()
#11 0x0000000000000000 in  ()

Thread 3 (Thread 0x7fc484af8640 (LWP 7899) "Finalizer"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c7be8 in __new_sem_wait_slow64.constprop.0 () at /lib64/libpthread.so.0
#2  0x000055ea68960078 in  ()
#3  0x000055ea68918c97 in  ()
#4  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#5  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7fc486bff640 (LWP 7898) "SGen worker"):
#0  0x00007fc4875cb9da in __futex_abstimed_wait_common64 () at /lib64/libpthread.so.0
#1  0x00007fc4875c5280 in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#2  0x000055ea689bf0f7 in  ()
#3  0x00007fc4875bf259 in start_thread () at /lib64/libpthread.so.0
#4  0x00007fc4874ca2b3 in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7fc4873c7740 (LWP 7896) "mono"):
#0  0x00007fc4874bf59f in poll () at /lib64/libc.so.6
#1  0x0000000041696bde in  ()
#2  0x0000000000000000 in  ()
[Inferior 1 (process 7896) detached]

=================================================================
        Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fc48752d085):0x7fc48752d075  f9 48 89 fa c5 f9 ef c0 83 e1 3f 83 f9 20 77 2b  .H........?.. w+
0x7fc48752d085  c5 fd 74 0f c5 fd d7 c1 85 c0 0f 85 eb 00 00 00  ..t.............
0x7fc48752d095  48 83 c7 20 83 e1 1f 48 83 e7 e0 eb 42 66 66 2e  H.. ...H....Bff.
0x7fc48752d0a5  0f 1f 84 00 00 00 00 00 0f 1f 00 83 e1 1f 48 83  ..............H.

=================================================================
        Managed Stacktrace:
=================================================================
          at <unknown> <0xffffffff>
          at System.Drawing.GDIPlus:GdipMeasureString <0x000fd>
          at System.Drawing.Graphics:GdipMeasureString <0x00103>
          at System.Drawing.Graphics:MeasureString <0x000a7>
          at System.Drawing.Graphics:MeasureString <0x0005f>
          at System.Drawing.Graphics:MeasureString <0x0009f>
          at ZedGraph.FontSpec:MeasureString <0x000a3>
          at ZedGraph.FontSpec:BoundingBox <0x00077>
          at ZedGraph.FontSpec:BoundingBox <0x0005f>
          at ZedGraph.Scale:GetScaleMaxSpace <0x00217>
          at ZedGraph.Scale:CalcMaxLabels <0x000d3>
          at ZedGraph.LinearScale:PickScale <0x0039f>
          at ZedGraph.GraphPane:PickScale <0x000bf>
          at ZedGraph.GraphPane:AxisChange <0x0011b>
          at ZedGraph.MasterPane:AxisChange <0x00083>
          at ZedGraph.ZedGraphControl:AxisChange <0x000cb>
          at : <0x00096>
          at : <0x002eb>
          at : <0x0064b>
          at : <0x0011f>
          at System.Threading.Tasks.Task:InnerInvoke <0x0006d>
          at System.Threading.Tasks.Task:Execute <0x0003b>
          at System.Threading.Tasks.Task:ExecutionContextCallback <0x0005f>
          at System.Threading.ExecutionContext:RunInternal <0x001b6>
          at System.Threading.ExecutionContext:Run <0x00047>
          at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x00113>
          at System.Threading.Tasks.Task:ExecuteEntry <0x000c7>
          at System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem <0x0002b>
          at System.Threading.ThreadPoolWorkQueue:Dispatch <0x002f6>
          at System.Threading._ThreadPoolWaitCallback:PerformWaitCallback <0x00063>
          at <Module>:runtime_invoke_bool <0x00086>
=================================================================
```

**Comment by QuantAsylum** [comment]
Fixed long ago

**Comment by f9207000** [comment]
> Fixed long ago

Could you tell me how you fixed it? I'm running c# code on linux with mono and I get the same error.
